### ISSUE TITLE
No longer works for P100 | error_code 1003

### ISSUE THREAD

**Issue by Mysteoa** [dswd/OctoPrint-PSUControl-Tapo#10]
I'm no longer able to activate my P100 with this plugin. 

I haven't changed anything. It was running fine 5 days ago and stopped 3 days ago. I didn't use Octoprint during those 2 days
It works fine from the app. I don't know if the Smart plug was updated, it's currently using FW ver. 1.2.1 build 230804 re. 190922

I activated the debug level for the plugin, and I'm getting "ERROR - Error: {'error_code': 1003}". I think is either failing to authenticate or to send the  request.

**Comment by fabkai** [comment]
I can confirm this: My Tapo P100 can also no longer be switched on and off via the plugin for a few days. I have also not changed anything.

**Comment by fabkai** [comment]
Seems to be a general problem since the last FW update:
https://github.com/openhab/openhab-addons/issues/15585
https://github.com/apatsufas/homebridge-tapo-p100/issues/46

**Comment by dswd** [comment]
I just fixed the plugin
