### ISSUE TITLE
Any plans on supporting Tapo P300 power strip?

### ISSUE THREAD

**Issue by fgiudice98** [dswd/OctoPrint-PSUControl-Tapo#16]
As in the title. I have my printer connected to a tapo P300, do you have any plans on supporting it?
Thanks in advance

**Comment by dswd** [comment]
Hi, I just looked into it and it seems to be more complex than just add P300 to the supported devices list.
Apparently the P300 has multiple sockets that you can control individually while the API I am using just tells the device to switch on / off. I am sorry but I don't see that coming. I don't own a P300 and the API is mostly undocumented, so it requires lots of googling / reverse engineering.

**Comment by fgiudice98** [comment]
Ok, thanks a lot for the answer
